//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workstation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MorgueEntities : DbContext
    {
        public MorgueEntities()
            : base("name=MorgueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Stuff> Stuff { get; set; }
        public virtual DbSet<Buildings> Buildings { get; set; }
        public virtual DbSet<Morgues> Morgues { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Operations> Operations { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
