//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workstation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Morgues
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Morgues()
        {
            this.Positions = new HashSet<Positions>();
            this.Operations = new HashSet<Operations>();
        }
    
        public int idMorgue { get; set; }
        public string address { get; set; }
        public string typeOfMorgue { get; set; }
        public string officialName { get; set; }
        public int workersAmount { get; set; }
        public string typeOfFinancing { get; set; }
    
        public virtual Buildings Buildings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Positions> Positions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operations> Operations { get; set; }
    }
}
