//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workstation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public int idMorgue { get; set; }
        public int idPatient { get; set; }
        public int idOperator { get; set; }
        public string nameOfOperatorsPosition { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Morgues Morgues { get; set; }
        public virtual Positions Positions { get; set; }
    }
}
